version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - '880:80'
      - '8443:443'
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./app:/app
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx

  php8.1-fpm:
    build: php8.1-fpm
    container_name: php8.1-fpm
    restart: always
    ports:
      - '9000:9000'
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./app:/app
      - ./php8.1-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./php8.1-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php8.1-fpm/logs:/usr/local/etc/php/var/log

  php8.1-cli:
    build: php8.1-cli
    container_name: php8.1-cli
    restart: always
    ports:
      - '9001:9001'
    environment:
      - TZ=Asia/Shanghai
    tty: true
    volumes:
      - ./app:/app
      - ./php8.1-cli/php.ini:/usr/local/etc/php/php.ini
      - ./php8.1-cli/logs:/usr/local/etc/php/var/log
      - ./php8.1-cli/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./php8.1-cli/supervisor/conf.d:/etc/supervisor/conf.d
    command: ["supervisord", "-n","-c", "/etc/supervisor/supervisord.conf"]